### ISSUE TITLE
background (toutes les pages)

### ISSUE THREAD

**Issue by ludoviccao** [CodeQRUltimate/CodeQRUltimate.github.io#15]
présentement toutes les pages montrent le background croppé d'à peu près une box au milieu des images
est-ce qu'il y aurait moyen de prendre environ le 2 et 3e sixième des images?

idem pour la page d'accueil

![image](https://user-images.githubusercontent.com/91299106/137042170-f93bf422-1c06-4a07-908b-f6208fcf8369.png)

![image](https://user-images.githubusercontent.com/91299106/137042232-6ab5c7ab-d97d-4eb4-ba4e-cc181ec1e822.png)

**Comment by kevinbourassahoule** [comment]
Jpourrais tu mettons te faire spécifier dans le data un pourcentage on the y-axis sur l'image où tu veux mettre le focus pis je peux assumer une valeur par défaut de genre 30%?
