### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by ludoviccao** [CodeQRUltimate/CodeQRUltimate.github.io#17]
la traduction fonctionne mais pas pour le contenu rédigé

![image](https://user-images.githubusercontent.com/91299106/137165731-fecf39dd-76fa-4899-ad99-e2b24fd76774.png)

**Comment by kevinbourassahoule** [comment]
Wait c'est quoi le problème, que tu peux pas traduire le contenu dans le data?  D'ailleurs, voulais-tu pouvoir le traduire?

**Comment by kevinbourassahoule** [comment]
kk jvais y penser mais la traduction va être manuelle for sure
