### ISSUE TITLE
Galerie / Gallery

### ISSUE THREAD

**Issue by ludoviccao** [CodeQRUltimate/CodeQRUltimate.github.io#25]
J'ai une shit tonne de photos, ca serait nice de pouvoir les uploader sur le site ! :O 

Un peu comme ton site de mariage, par album (les albums étant les dates à laquelle les photos ont été prises)

J'irai pas au point de tagger les individus mais si cest pas long à faire et je peux le faire moi-même. Why the fuck not

**Comment by kevinbourassahoule** [comment]
@ludoviccao par upload tu veux dire via github right, pas via l'interface?

**Comment by ludoviccao** [comment]
@kevinbourassahoule  oui, moi jveux les uploader

**Comment by kevinbourassahoule** [comment]
@ludoviccao ok ben tu peux deja les organiser dans le dossier `img` de la branche `data` in a way that makes sense to you pis on pourra rajouter ca dans le Excel, avec les tags peut-etre, pis tu feras un rough sketch de cque tu veux voir sur la page, ou au moins une description de quoi ajouter où

**Comment by ludoviccao** [comment]
@ludoviccao  veux tu un jamboard??? hahaha

**Comment by kevinbourassahoule** [comment]
@ludoviccao why not, works for me

**Comment by ludoviccao** [comment]
@kevinbourassahoule [https://jamboard.google.com/d/1SyiOJivSP1sh60w3goyecZyajgnl_53gm1ZK_Wyb5EM/viewer?f=8&pli=1](https://jamboard.google.com/d/1SyiOJivSP1sh60w3goyecZyajgnl_53gm1ZK_Wyb5EM/viewer?f=8&pli=1)

**Comment by kevinbourassahoule** [comment]
cmb tu penses en avoir par date mettons

**Comment by kevinbourassahoule** [comment]
@ludoviccao ^

**Comment by ludoviccao** [comment]
pas plus que 10 genre
