### ISSUE TITLE
Font uniformization

### ISSUE THREAD

**Issue by ludoviccao** [CodeQRUltimate/CodeQRUltimate.github.io#3]
Il faudrait que la typo soit pareille partout.
Présentement, la typo des noms de joueurs est la plus hot. Est-ce qu'on peut l'appliquer partout?
![image](https://user-images.githubusercontent.com/91299106/136090377-8a94c140-206f-4bf6-bdc9-554c12ff08f6.png)

**Comment by kevinbourassahoule** [comment]
Cancelle ca, tu feras un autre issue pour choisir quel font utiliser for "normal" text
